name: Hongik Job Alarm

on:
  schedule:
    - cron: '*/27 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 가상 모니터 설치
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb

      - name: 라이브러리 설치
        run: |
          pip install beautifulsoup4 python-telegram-bot selenium webdriver-manager pyvirtualdisplay

      - name: 크롤링 코드 실행
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          HONGIK_ID: ${{ secrets.HONGIK_ID }}
          HONGIK_PW: ${{ secrets.HONGIK_PW }}
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" python main.py
      
      - name: 결과 텍스트 저장
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sent_posts.txt
          git commit -m "Update sent posts" || exit 0
          git pull origin main --rebase
          git push
